### 회원가입 (고객)
POST http://localhost:8081/signUp/customer
Content-Type: application/json

{
  "birth" : "98-09-22",
  "email" : "h2ju1004@gmail.com",
  "name" : "ryureeru",
  "password" : "pw",
  "phone" : "01000000000"
}

### 이메일 인증 (고객)
GET http://localhost:8081/signUp/customer/verify?email=h2ju1004@gmail.com&code=

### 로그인 (고객)
POST http://localhost:8081/signIn/customer
Content-Type: application/json

{
  "email" : "h2ju1004@gmail.com",
  "password" : "pw"
}

### 회원 정보 조회 (고객)
GET http://localhost:8081/customer/getInfo
Content-Type: application/json
X-AUTH-TOKEN:

### 잔액 변경 (고객)
POST http://localhost:8081/customer/balance
Content-Type: application/json
X-AUTH-TOKEN:

{
  "from" : "server",
  "message" : "돈 충전",
  "money" : 50000
}

#############################

### 회원가입 (셀러)
POST http://localhost:8081/signUp/seller
Content-Type: application/json

{
  "birth" : "98-09-22",
  "email" : "h2ju1004@gmail.com",
  "name" : "ryureeru",
  "password" : "pw",
  "phone" : "01000000000"
}

### 이메일 인증 (셀러)
GET http://localhost:8081/signUp/seller/verify?email=h2ju1004@gmail.com&code=

### 로그인 (셀러)
POST http://localhost:8081/signIn/seller
Content-Type: application/json

{
  "email" : "h2ju1004@gmail.com",
  "password" : "pw"
}
