### 상품 추가
POST http://localhost:8082/seller/product
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJocjRMaEFObVZMYmYvc0JlZmdudnJ4M3Q2N0xMWUllVjNRTW8xYmtJK29NPSIsImp0aSI6IlN1YkhlS1VSUnJlUVkrV1NPbkJrdGc9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjc1MDg4MTg4LCJleHAiOjE2NzUxNzQ1ODh9.nnsYeywQvSEgT3egjpecWImcqan_Z9wjWv6NGAVa12A

{
  "description": "상품 설명",
  "items": [
    {
      "count": 1,
      "name": "230",
      "price": 10000
    }
  ],
  "name": "나이키 에어포스"
}

### 상품 아이템 추가
POST http://localhost:8082/seller/product/item
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJocjRMaEFObVZMYmYvc0JlZmdudnJ4M3Q2N0xMWUllVjNRTW8xYmtJK29NPSIsImp0aSI6IlN1YkhlS1VSUnJlUVkrV1NPbkJrdGc9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjc1MDg4MTg4LCJleHAiOjE2NzUxNzQ1ODh9.nnsYeywQvSEgT3egjpecWImcqan_Z9wjWv6NGAVa12A

{
  "productId" : 1,
  "count": 1,
  "name": "235",
  "price": 10000
}